<?php
function red_if_zero($value) {
	return sprintf($value > 0 ? '%d' : '<strong>%d</strong>', $value);
}
?>
<!DOCTYPE html>
<html>
	<head>
		<title>Analyse <?=$this->html($kb->title)?></title>
		<link rel="stylesheet" href="webfrontend.css">
		<style>
			th {
				text-align: left;
			}
			td:nth-child(1) {
				width: 200px;
			}

			td strong {
				color: red;
			}

			h3 {
				border-top: 1px solid silver;
				padding: 1em 0;
			}

			h3 small {
				font-weight: normal;

			}

		</style>
	</head>
	<body>
		<nav>
			<a href="webfrontend.php?kb=<?=urlencode($_GET['kb'])?>">Start <?=$this->html($kb->title)?></a>
        	<a href="index.php">Kennisbanken</a>
		</nav>
        
        <header>
                <h1>Analyse <?=$this->html($kb->title)?></h1>
                <p>Uiteenzetting van alle vragen, regels en afhankelijkheden in deze kennisbank.</p>
        </header>
		
		<dl class="stats">
			<dt>Aantal regels:</dt>
			<dd><?=count($kb->rules)?></dd>
			
			<dt>Aantal vragen:</dt>
			<dd><?=count($kb->questions)?></dd>
		</dl>
		<?php foreach ($stats as $fact): ?>
		<h3>
			<?=$this->html($fact->name)?>
			<small>(<a href="webfrontend.php?kb=<?=urlencode($_GET['kb'])?>&goals=<?=urlencode($fact->name)?>">leidt alleen dit feit af</a>)</small>
		</h3>
		<table>
			<thead>
				<tr>
					<th>Waarde</th>
					<th>Afleidende vragen</th>
					<th>Afleindende regels</th>
					<th>Afleidende regels + vragen</th>
					<th>Testende regels</th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($fact->values as $value => $value_stats): ?>
				<tr>
					<td><?=$this->html($value)?></td>
					<td><?=count($value_stats->inferringQuestions)?></td>
					<td><?=count($value_stats->inferringRules)?></td>
					<td><?=red_if_zero(count($value_stats->inferringQuestions) + count($value_stats->inferringRules))?></strong></td>
					<td><?=red_if_zero(count($value_stats->dependingRules))?></td>
				</tr>
			<?php endforeach ?>
			</tbody>
		</table>
		<?php endforeach ?>
	</body>
</html>