<section class="completed">
	<h2>Conclusions</h2>
	<dl>
	<?php foreach ($state->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name]->value != STATE_UNDEFINED)): ?>
			<dt><?=$state->substitute_variables($goal->description, ['Template', 'html'])?></dt>
			<dd><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name]->value . '</pre>';
				?></p>
				<div class="explanation">
					<ol><?= $formatter->formatReason($state->facts[$goal->name]->reason) ?></ol>
				</div>
			<?php endif ?>
	<?php endforeach ?>
</section>
