<section class="completed">
	<h2>Verdict</h2>
	
	<?php foreach ($state->goals as $goal): ?>
		<?php if ($goal->hasAnswers() && (($answer = $goal->answer($state)) || $state->facts[$goal->name]->value != STATE_UNDEFINED)): ?>
			<section>
				<p><?=$goal->description?></p>
				<p><?php
				echo $answer
					? $state->substitute_variables($answer->description, ['Template', 'html'])
					: '<pre>' . $state->facts[$goal->name]->value . '</pre>';
				?></p>
				<div class="explanation">
					<ol><?= $formatter->formatReason($state->facts[$goal->name]->reason) ?></ol>
				</div>
			<?php endif ?>
	<?php endforeach ?>

</section>
