<!DOCTYPE html>
<html>
	<head>
		<title>Kennisbanken</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="kennisbanken">
		<nav>
			<!-- what should come here? -->
		</nav>
		<header>
			<h1>Kennisbanken</h1>
			<p>Kies een kennisbank om te doorlopen of upload een nieuwe.</p>
		</header>

		<?php if ($message): ?>
		<p class="status-update"><?=$message?></p>
		<?php endif ?>

		<ul class="kennisbanken">
			<?php foreach ($knowledge_bases as $path):
				$file = basename($path); ?>
			<li>
				<a href="webfrontend.php?kb=<?=urlencode($file)?>" class="run">Start <?=$this->html($file)?></a>
				<span class="last-modified">Laatst bijgewerkt <time title="<?=date('c', filemtime($path))?>"><?=date('\o\p d-m, \o\m H:i', filemtime($path))?></time></span>
				<a href="download.php?kb=<?=urlencode($file)?>" class="download">download</a>
				<a href="analyse.php?kb=<?=urlencode($file)?>" class="analyse">
				analyseer</a>
				<form method="post">
					<input type="hidden" name="delete-file" value="<?=$this->attr($file)?>">
					<button type="submit" class="delete">Verwijder</button>
				</form>
			</li>
			<?php endforeach ?>
		</ul>
		
		<form method="post" enctype="multipart/form-data">
			<input type="file" name="knowledgebase">
			<button type="submit">Voeg toe</button>
		</form>
	</body>
</html>