<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->html($state->title) ?></title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="webfrontend">
		<nav>
			<a href="index.php">Kennisbanken</a>
			<a href="webfrontend.php?kb=<?=$_GET['kb']?>">Start overnieuw</a>
		</nav>
		<header>
			<h1><?=$this->html($state->title)?></h1>
			<p><?=$state->description?></p>
		</header>
		<div>
			<form method="post">
				<input type="hidden" name="state" value="<?=_encode($state) ?>">
				<?=$content?>
			</form>
		</div>
		<aside id="fact-state" class="state-info">
			<h3>Feiten</h3>
			<dl>
				<?php foreach($state->facts as $name => $value): ?>
				<dt><?=$name?></dt>
				<dd><?=$value?></dt>
				<?php endforeach ?>
			</dl>
		</aside>
		<aside id="goal-stack" class="state-info">
			<h3>Goal stack</h3>
			<ol>
				<?php foreach ($state->goalStack as $goal): ?>
				<li><?=$goal?></li>
				<?php endforeach ?>
			</ol>
		</aside>
		<script>
		Array.prototype.forEach.call(
			document.querySelectorAll('.question > .options > li'),
			function(option) {
				option.classList.add('single-click');
				option.addEventListener('click', function(e) {
					if (e.target.nodeName == 'A')
						return;

					var radio = option.querySelector('input[type=radio]');
					radio.checked = true;
					e.preventDefault();
					radio.form.submit();
				});
			});
		</script>
	</body>
</html>