<section class="question">
	<p><?=$question->description?></p>

	<ol class="options">
		<?php foreach ($question->options as $option): ?>
		<li>
			<label>
				<input type="radio" name="answer" value="<?=_encode($option->consequences)?>">
				<?=$option->description?>
			</label>
		</li>
		<?php endforeach ?>
		<?php if($question->skippable): ?>
		<li class="skip-option">
			<label>
				<input type="radio" name="answer" value="<?=_encode(array())?>">
				I don't know
			</label>
		</li>
		<?php endif ?>
	</ol>

	<button type="submit">Continue…</button>
</section>
