<nav class="page-nav">
	<ol>
		<li><a href="#how-it-works">How it works</a></li>
		<ol>
			<li><a href="#tools">Tools</a></li>
			<li><a href="#order-of-execution">Order of execution</a></li>
		</ol>
		<li><a href="#knowledge-bases">Writing a knowledge base</a></li>
		<ol>
			<li><a href="#fact">Facts</a></li>
			<li><a href="#goal">Goals</a></li>
			<li><a href="#rule">Rules</a></li>
			<li><a href="#question">Questions</a></li>
		</ol>
	</ol>
</nav>

<section class="help">
	<p><strong>Quick start:</strong> Download <a href="knowledge-base-example.xml" download="knowledge-base-example.xml">knowledge-base-example.xml</a> (<a href="webfrontend.php?kb=knowledge-base-example.xml">run it</a>, <a href="view.php?kb=knowledge-base-example.xml">view it</a>) and read the comments to get familiar with the knowledge base format. Modify the file, upload it here and select <em>Run</em> to run it.</p>

	<p>If you have a question or are stuck, you should ask your Teaching Assistant. If you notice a bug or have an idea to improve this system, <a href="https://github.com/jelmervdl/kennissysteem/issues">please file an issue on Github</a>.</p>
</section>

<section id="how-it-works" class="help">
	<h2>How it works</h2>
	<p>After uploading your knowledge base, the program uses it to ask questions and come to a conclusion. It works like a simple <abbr title="Question answering">QA</abbr>-system. At anytime you can open the debug panel to view the current state of facts, questions, rules etc.</p>

	<p>A knowledge base used by this program consists of <a href="#rule">rules</a>, <a href="#question">questions</a> and one or multiple <a href="#goal">goals</a>. Both rules and questions can yield knowledge which is stored in <a href="#fact">facts</a>.</p>

	<p>The program will try to infer the value of goals by looking for rules it can apply using the knowledge it already has. If it doesn't find any rules for which all the facts in the <tt>&lt;if&gt;</tt>-clause are known, it will add the unknown facts to the goal stack. It will also look for questions that could yield the facts looked for and will ask the one that has the most impact on the state of the knowledge base.</p>

	<p id="closed-world-assumption">Note that this program uses a closed world assumption: if it cannot decide the value of a fact based on rules or questions, it will assign it the value <tt>undefined</tt>. You should never use that litteraly in your knowledge base, but you can make use of the fact that <tt>undefined</tt> is not equal to <tt>yes</tt> or some other value.</p>

	<section id="tools">
		<h3>Tools</h3>
		<p>This website has a few tools available to help you with understanding what is happening.</p>
		<p>When a question is asked, click the <em>Debug</em> button in the top bar to open the debug sidebar. This shows you the current known facts, the goal stack, the rules that are not yet applied and a step by step log of what has already happened.</p>

		<p>Another option is the <em>Analyse</em> button. Here you can see the program try to infer all possible values of facts in your knowledge base and whether they are inferred or tested by rules. A rule infers a fact if it occurs in the <tt>&lt;then&gt;</tt>-clause, and tested if it occurs in the <tt>&lt;if&gt;</tt>-clause.</p>
	</section>

	<section id="order-of-execution">
		<h3>Order of execution</h3>
		<p><a href="https://github.com/jelmervdl/kennissysteem/blob/master/solver.php">The solver</a> uses a simple loop to infer stuff:</p>
		<ol>
			<li>The solver starts when <tt>bachwardChain()</tt> is called:</li>
			<ol>
				<li>While there are still goals on the goal stack:</li>
				<ol>
					<li>Try to solve the top most goal (see the <tt>solve</tt> function):</li>
					<ol>
						<li>Check the current value of the goal</li>
						<li>If it is already a Yes or No, (i.e. it was already inferred during the forward chaining step) continue to to the next goal in the stack.</li>
						<li>If there are rules that can infer this fact, add those to the goal stack if they are not already in there. (These rules cannot yet infer this fact because otherwise they would already have done so during the forward chaining step.)</li>
						<li>If there are no rules but there are questions that can be asked to infer the fact, ask one of those.</li>
						<li>Otherwise, set the fact to <tt>$unknown</tt>.</li>
					</ol>
				</ol>
				<li>If a question was asked, show that on the screen and stop.</li>
				<li>As soon as it is answered, add the answer to the set of facts and start again with <tt>bachwardChain()</tt>.</li>
			</ol>
		</ol>
	</section>

</section>

<section class="help">
	<h2>Writing a knowledge base</h2>
	<p>The knowledge base is written using simple XML. Globally, your file will look something like this:</p>
	<code><pre>
&lt;knowledge&gt;
	&lt;title&gt;My test kb&lt;/title&gt;
	&lt;description&gt;Decide whether to take a course.&lt;/description&gt;

	&lt;!-- Here follow multiple rules, questions and goals --&gt;

	&lt;!-- And yes, you can use this syntax to add
	     comments to your knowledge base :) --&gt;
&lt;/knowledge&gt;
</pre></code>

	<p>You can download and run <a href="knowledge-base-example.xml">knowledge-base-example.xml</a> (<a href="webfrontend.php?kb=knowledge-base-example.xml">run it</a>, <a href="view.php?kb=knowledge-base-example.xml">view it</a>) as a start and modify it to fit your needs. It contains comments explaining all the rules and clauses.</p>

	<section id="fact">
		<h3>Facts</h3>
		<p>The most atomic part of this reasoning engine are little <code>&lt;fact&gt;</code> elements. They are what it tries to derive and they are the fundamental elements of all the rules, as you will see in the next sections.</p>
		<code><pre>
&lt;fact name="follow-course"&gt;yes&lt;/fact&gt;
</pre></code>
		<p>A fact always has a name specified using the attribute <tt>name</tt> and a value. A name could be <tt>follow-course</tt> and the value could be <tt>yes</tt>, <tt>no</tt>, <tt>whatever-you-like</tt> or <tt>undefined</tt>. The last value is a bit special, as this is the value the inference engine gives a fact when there are no more rules nor questions which can give the fact a value. I like to treat <tt>undefined</tt> as an implicit <em>no, because it is not yes as far as I know</em>.</p>
	</section>

	<section id="goal">
		<h3>Goals</h3>
		<p>Goals are the facts that your knowledge base is trying to answer and are the initial elements on the goal stack. At the end, the conclusion for each goal is shown. For example, if your knowledge base is written for answering whether you should follow a course it will show you what it recommends.</p>
		<code><pre>
&lt;goal name="follow-course"&gt;
	&lt;description&gt;Should you follow the course?&lt;/description&gt;
	&lt;answer value="yes"&gt;Yes, you should&lt;/answer&gt;
	&lt;answer value="no"&gt;No, you should not&lt;/answer&gt;
	&lt;answer&gt;You should decide for yourself&lt;/answer&gt;
&lt;/goal&gt;
</pre></code>
		<p>The last cause does not explicitly test for a value, which will make it test for the <tt>undefined</tt> value. See <a href="#closed-world-assumption">the closed world assumption.</a></p>
	</section>

	<section id="rule">
		<h3>Rules</h3>
		<p>The inference engine tries to gain new knowledge by applying rules. The rules, however, are very straightforward if-then rules. They also have a description but that is just there to help you remember what the rules encode. The most basic example of a rule:</p>
		<code><pre>
&lt;rule&gt;
	&lt;description&gt;If the course is mandatory,
	  you should follow this course.&lt;/description&gt;
	&lt;if&gt;
		&lt;fact name="course-is-mandatory"&gt;yes&lt;/fact&gt;
	&lt;/if&gt;
	&lt;then&gt;
		&lt;fact name="follow-course"&gt;yes&lt;/fact&gt;
	&lt;/then&gt;
&lt;/rule&gt;
</pre></code>
		<p>Furthermore, you can use <code>&lt;and&gt;</code>, <code>&lt;or&gt;</code> and &lt;not&gt; clauses to form more complex rules:</p>
		<code><pre>
&lt;rule&gt;
	&lt;description&gt;If the course is mandatory or fun,
	  you should follow this course.&lt;/description&gt;
	&lt;if&gt;
		&lt;or&gt;
			&lt;fact name="course-is-mandatory"&gt;yes&lt;/fact&gt;
			&lt;fact name="course-is-fun"&gt;yes&lt;/fact&gt;
		&lt;/or&gt;
	&lt;/if&gt;
	&lt;then&gt;
		&lt;fact name="follow-course"&gt;yes&lt;/fact&gt;
	&lt;/then&gt;
&lt;/rule&gt;
</pre></code>
		<p>You can nest those as deep as you want. However, most of the time it is easier to chain a few rules. For example, writing two rules: <tt>if (teacher-is-interesting = yes and material-is-interesting = yes) then course-is-fun = yes</tt> and <tt>if (course-is-fun = yes or course-is-mandatory = yes) then follow-course = yes</tt> instead of <tt>if (teacher-is-interesting = yes and material-is-interesting = yes) or (course-is-mandatory = yes) then follow-course = yes</tt>. As for all programming challenges, less complex rules are almost always better.</p>
	</section>

	<section id="question">
		<h3>Questions</h3>
		<p>You cannot test your knowledge base without data from the outside. So as some facts can be derived from rules inside the knowledge base, such as <tt>follow-course</tt>, others like <tt>material-is-interesting</tt> need to be asked to the user of the system. This can be done by defining questions for such facts:</p>
		<code><pre>
&lt;question&gt;
	&lt;description&gt;If the material of the course interesting?&lt;/description&gt;
	&lt;option&gt;
		&lt;description&gt;The material is very interesting&lt;/description&gt;
		&lt;then&gt;
			&lt;fact name="material-is-interesting"&gt;yes&lt;/fact&gt;
		&lt;/then&gt;
	&lt;/option&gt;
	&lt;option&gt;
		&lt;description&gt;It is utterly boring&lt;/description&gt;
		&lt;then&gt;
			&lt;fact name="material-is-interesting"&gt;no&lt;/fact&gt;
		&lt;/then&gt;
	&lt;/option&gt;
&lt;/question&gt;
</pre></code>
	</section>
</section>