<!DOCTYPE html>
<html>
	<head>
		<title>Inference engine</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="kennisbanken">
		<nav class="site-nav">
			<!-- what should come here? -->
		</nav>
		<header>
			<h1>Inference engine</h1>
		</header>

		<?php if ($errors): ?>
		<section class="status-update">
			<p>The following errors occurred:</p>
			<ul>
				<?php foreach ($errors as $error): ?>
				<li title="<?=$this->attr(sprintf('%s:%d', $error->file, $error->line))?>"><?=$this->html($error->message)?></li>
				<?php endforeach ?>
			</ul>
		</section>
		<?php endif ?>

		<section class="upload-knowledge-base-form">
			<h2>Run a knowledge base</h2>
			<form method="post" enctype="multipart/form-data">
				<div>
					<label for="input-knowledgebase">Knowledge base XML file:</label>
					<input type="file" name="knowledgebase" id="input-knowledgebase">
				</div>

				<div class="controls">
					<button type="submit" name="action" value="run">Run</button>
					<button type="submit" name="action" value="analyse">Analyse</button>
				</div>
			</form>
		</section>

		<?php include dirname(__FILE__) . '/reference.phtml' ?>

		<footer>
			<p>Source code available on <a href="https://github.com/jelmervdl/kennissysteem">Github</a>.</p>
		</footer>

		<script>
			Array.prototype.forEach.call(
				document.querySelectorAll("a[href^='#']"),
				function(el) {
					console.log(el);
					el.addEventListener('click', function() {
						var hash = el.href.substring(el.href.indexOf('#') + 1);
						var ref = document.getElementById(hash);
						
						Array.prototype.forEach.call(
							document.querySelectorAll('.highlight'),
							function(node) {
								node.classList.remove('highlight')
							});
						
						if (ref)
							ref.classList.add('highlight');
					});
				});
		</script>
	</body>
</html>
