<!DOCTYPE html>
<html>
	<head>
		<title>Inference engine</title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body id="kennisbanken">
		<nav>
			<!-- what should come here? -->
		</nav>
		<header>
			<h1>Inference engine</h1>
		</header>

		<?php if ($errors): ?>
		<section class="status-update">
			<p>The following errors occurred:</p>
			<ul>
				<?php foreach ($errors as $error): ?>
				<li title="<?=$this->attr(sprintf('%s:%d', $error->file, $error->line))?>"><?=$this->html($error->message)?></li>
				<?php endforeach ?>
			</ul>
		</section>
		<?php endif ?>

		<section class="upload-knowledge-base-form">
			<h2>Run a knowledge base</h2>
			<form method="post" enctype="multipart/form-data">
				<div>
					<label for="input-knowledgebase">Knowledge base XML file:</label>
					<input type="file" name="knowledgebase" id="input-knowledgebase">
				</div>

				<div class="controls">
					<button type="submit" name="action" value="run">Run</button>
					<button type="submit" name="action" value="analyse">Analyse</button>
				</div>
			</form>
		</section>
		<footer>
			<p>Source code available on <a href="https://github.com/jelmervdl/kennissysteem-brandveiligheid">Github</a>.</p>
		</footer>
	</body>
</html>
