<!DOCTYPE html>
<html>
	<head>
		<title>View <?=self::html(basename($file))?></title>
		<link rel="stylesheet" href="webfrontend.css">
	</head>
	<body>
		<nav class="site-nav">
			<a href="webfrontend.php?kb=<?=urlencode($_GET['kb'])?>">Run <?=self::html(basename($file))?></a>
        	<a href="index.php">Upload</a>
		</nav>
        
        <section class="xml-readout">
	        <code class="numbered">
		        <pre data-lineno="1">&lt;?xml version="1.0"?&gt;</pre>
				<pre data-lineno="2">&lt;knowledge&gt;</pre>
			</code>
	        <?php foreach (new DOMNodeIterator($document->firstChild->childNodes) as $node): ?>
	        <?php if ($node->nodeType == XML_ELEMENT_NODE): ?>
			<code class="numbered"><?=self::format_code($document->saveHTML($node), $node->getLineNo())?></code>
			<?php elseif ($node->nodeType == XML_COMMENT_NODE): ?>
			<div class="comment"><?=self::format_plain_text($node->data)?></div>
			<?php endif ?>
			<?php endforeach ?>
			<code class="numbered"><?=self::format_code('</knowledge>')?></pre></code>
		</section>
        
		<footer>
			<p>Source code available on <a href="https://github.com/jelmervdl/kennissysteem">Github</a>.</p>
		</footer>
	</body>
</html>
